spring:
  application:
    name: spring-sql-demo
    description: A demo project for a RESTful Service connected to a SQL DB.
    version: "@application.version@"
    timestamp: "@application.buildTimestamp@"
    branch: "@application.branch@"
    environment: ${ENV}
  profiles.active: default
  data:
    mongodb:
      #uri: "mongodb://${MONGODB_USER}:${MONGODB_PW}@${MONGODB_SERVICE_NAME}:27017/${MONGODB_NAME}?authSource=${MONGODB_USER}&connectTimeoutMS=${MONGODB_CONNECT_TIME}&socketTimeoutMS=${MONGODB_SOCKET_TIME}&serverSelectionTimeoutMS=${MONGODB_SERVER_TIME}"
      uri: ${MONGODB_SERVICE_NAME}
      database: "testdb"

api:
  basePath: "api/"
  version:
    v1: "v1"
    v2: "v2"

server:
  port: 8080
  servlet:
    contextPath: "/${spring.application.name}"

logback:
  appender: STDOUT_COLOR
  level: DEBUG

springfox:
  documentation:
    auto-startup: true